name: Automatic Semantic Release Workflow

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - main
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN}}
        run: |
          npm install
          npx semantic-release

  success:
    runs-on: ubuntu-latest
    needs:
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}